### ISSUE TITLE
line is too big

### ISSUE THREAD

**Issue by imed-ghomari** [linjunpop/obsidian-progress#1]
In reading view, It doesn't render like the image in README
![image](https://user-images.githubusercontent.com/38974541/165141343-142696b8-acaa-4914-b115-8525ac506303.png)
the progress line is too thick
![image](https://user-images.githubusercontent.com/38974541/165141451-4e6f280a-db7a-4a57-a8c9-0af05d083382.png)

**Comment by imed-ghomari** [comment]
and in live preview, it renders like this 
![image](https://user-images.githubusercontent.com/38974541/165142009-0f80c887-0f59-4a16-aa9b-f8aa703bcaa9.png)

**Comment by linjunpop** [comment]
Hi @imeed166,

`0.3.0` is released and the badge won't take whole line to display.

But it still render incorrectly in the Live Preview, I will check later.

**Comment by imed-ghomari** [comment]
Also, in reading mode, in dark mode, the text is not readable.
![image](https://user-images.githubusercontent.com/38974541/165185648-91cfa761-6b1f-4650-a7b5-0fbf8f656e7a.png)

**Comment by linjunpop** [comment]
Live Preview rendering has been fixed.

I will tweak the default style for better contract.

**Comment by linjunpop** [comment]
Live Preview rendering has been fixed.

I will tweak the default style for better contract.
